### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by femtotrader** [Weswit/Lightstreamer-example-StockList-client-python#1]
Hello,

it will be nice to split your example into a real python library (pip installable) and have a sample which use  your library.
see https://docs.python.org/2/distutils/setupscript.html
see https://github.com/pypa/sampleproject
so it will be much easier to reuse your code

You could also provide Continuous Integration through Travis (if you have a LightStreamer server available)

You can have a look at my project https://github.com/femtotrader/pandas_datareaders
to see how to do this

Kind regards

**Comment by gfinocchiaro** [comment]
Hi,

the original idea was not to build a real library and to make it as pip installable, but just to write a very minimal exercise to show a working interaction with the Lighstreamer Text Protocol in python.

In any case, we will take in consideration your precious suggestions on how to improve such little experiment in order to make it a starting layer for further extensions.

Thanks a lot!
Regards,
Gianuca

**Comment by femtotrader** [comment]
Hi,

Thanks. You can find an other example of pip package here:
https://github.com/femtotrader/ig-markets-rest-api-python-library
this project is using IG Markets REST API.

It will be nice if you could help on https://github.com/femtotrader/ig-markets-stream-api-python-library
this project is trying to use IG Markets streaming API.

KInd regards

Femto

**Comment by femtotrader** [comment]
A lot of code cleanup have been done in
https://github.com/ig-python/ig-markets-stream-api-python-library/

see
https://github.com/ig-python/ig-markets-stream-api-python-library/blob/master/sample/main.py

but it's still using igls (and so there is no Python 3 support)

I think it will be great to merge our efforts because we could be able to have a (minimal) Python Lighstreamer library which could be use by both https://github.com/Weswit/Lightstreamer-example-StockList-client-python/ and https://github.com/ig-python/ig-markets-stream-api-python-library/
