### ISSUE TITLE
i need a python client for server version 7

### ISSUE THREAD

**Issue by thinkingparticle** [Weswit/Lightstreamer-example-StockList-client-python#11]
this client is incompatible with lightstreamer server versions above 6.1 
I need a python client that works with lightstreamer server version 7. can you provide it?

**Comment by gfinocchiaro** [comment]
The client is "obsolete", but still working for Lighstreamer version 7 and above.

**Comment by AlessandroAlinone** [comment]
As of release v2.0 of this demo, the minimum required server version has become 7.2.0.
