### ISSUE TITLE
small T

### ISSUE THREAD

**Issue by csy08** [Weswit/Lightstreamer-example-StockList-client-python#12]
https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-python/blob/d19cc162e41fc2c4e6f5ce191928b90a25aad562/src/stock_list_demo.py#L295

**Comment by gfinocchiaro** [comment]
Could you please expand on this?

**Comment by csy08** [comment]
The documentation has `LS_table` https://www.lightstreamer.com/repo/distros/Lightstreamer_Allegro-Presto-Vivace_6_0_1_20150730.zip%23/Lightstreamer/DOCS-SDKs/sdk_client_generic/doc/Network%20Protocol%20Tutorial.pdf
