### ISSUE TITLE
Typo when importing lightstreamer.client in stock_list_demo.py

### ISSUE THREAD

**Issue by ilekilek** [Weswit/Lightstreamer-example-StockList-client-python#13]
The import command in line 17 of stock_list_demo.py should be changed from...

`from lightstreamer_client import *`

to...

`from lightstreamer.client import *`

https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-python/blob/0daede40d9d4878481c947464b49c33c47d921d1/src/stock_list_demo.py#LL17C13-L17C13

**Comment by acarioni** [comment]
Demo fixed and tested with Python SDK 1.0.2. Thanks for the report.
