### ISSUE TITLE
ValueError in _forward_update_message()

### ISSUE THREAD

**Issue by IanMichaelAsh** [Weswit/Lightstreamer-example-StockList-client-python#8]
I have an instance of the LSClient connecting to IG Index's LightStreamer server. 

I see an intermittent ValueError exception that occurs in _forward_update_message() while receiving a price stream from IG Index.

The offending line of code is "table, item = int(tok[0]), tok[1]" and the exception reason is "invalid literal for int() with base 10: ''"

A debug log file is attached showing the trail of messages leading to the exception.

**Comment by gfinocchiaro** [comment]
Few changes that should resolve the issue. In particular, disconnection now sends an explicit "destroy" command to the server. Furthermore, logging has been improved to capture more useful information in case of any possible issue.
Please test them and get back to us with any news.

**Comment by IanMichaelAsh** [comment]
Client has been running for 6 days without re-occurrence of issue, so appears to be resolved.
