### ISSUE TITLE
Problem In Subscribing Data

### ISSUE THREAD

**Issue by omibo** [Weswit/Lightstreamer-example-StockList-client-python#9]
I am trying to connect to a server and subscribe some fields. Fortunately I connect to server successfully. But I cant subscribe elements. Could you please help??

subscription = Subscription(
    mode="MERGE",
    items = ["IRO1BTEJ0001_lightrlc"],
    fields=["BestBuyLimitPrice_1"],
    adapter= "TadbirLightRLC"
)

**Comment by gfinocchiaro** [comment]
Hi,

can you provide any log?

**Comment by gfinocchiaro** [comment]
Closed as no more information provided.
